export default {
  ZONES_RECEIVED: 'ZONES_RECEIVED',
  ZONE_CREATED: 'ZONE_CREATED',
  SELECT_ZONE: 'SELECT_ZONE',

  COMMENTS_RECEIEVED: 'COMMENTS_RECEIEVED',
  COMMENT_CREATED: 'COMMENT_CREATED',

  CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
  PROFILE_RECEIVED: 'PROFILE_RECEIVED',

  APPLICATION_STATE: 'APPLICATION_STATE',

  PROFILED_UPDATED: 'PROFILED_UPDATED',

  COMMENT_UPDATED: 'COMMENT_UPDATED'
}
